# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: ClairB
email: c.barrass@epcc.ed.ac.uk
full_name: ClairB
github_organization: clairbarrass
keywords: sweet, desert
license: GNUv3
package_name: baklava
package_short_description: Sweet
template_profile: minimum
version: 0.1.0
